# This is a basic workflow to help you get started with Actions

name: My-GitHubAactions-Basics
env:
  APPLICATION_NAME    : "MyFlask"
  DEPLOY_PACKAGE_NAME : "flash-deploy-ver-${{ github.sha }}"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 my_testing:
   runs-on: ubuntu-latest
   steps:
   - name: Print Hello Message in Testing
     run: echo "Hello World from Testing job"
   - name: Execute few commands
     run: |
      echo "Hello Message1"
      echo "Hello Message2"
      echo "Aplication name: ${{ env.APPLICATION_NAME }}"
  
 my_deploy:
   runs-on: ubuntu-latest
   needs: [my_testing]
   
   steps:
   - name: Print Hello Message in Deploy
     run: echo "Hello World from Deploy job"
   - name: Deployment package
     run: echo "Deploy package name: ${{ env.DEPLOY_PACKAGE_NAME }}"
